[tox]
env_list = py314, py310, py311
skipsdist = True

[testenv]
deps = -rrequirements.txt
commands =
    pytest tests/unit/test_diffusion2d_functions.py
    pytest tests/integration/test_diffusion2d.py
